spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/issuetracker_dev
    username: postgres
    password: postgres123

  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.issuetracker: DEBUG
    org.hibernate.SQL: DEBUG
